# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "door"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_door_faceDoor_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(200.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(200.0000, 482.7264, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(200.7480, 500.0081, 0)
	P004 = App.Vector(202.9866, 517.1606, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(279.6565, 916.1094, 0)
	P006 = App.Vector(369.7107, 1312.2516, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(428.0484, 1520.2768, 0)
	P008 = App.Vector(500.0000, 1723.9941, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(580.3300, 1891.2344, 0)
	P010 = App.Vector(684.8164, 2044.5472, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(736.0815, 2085.4150, 0)
	P012 = App.Vector(800.0000, 2100.0000, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(863.9185, 2085.4150, 0)
	P014 = App.Vector(915.1836, 2044.5472, 0)
	S007 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(1019.6700, 1891.2344, 0)
	P016 = App.Vector(1100.0000, 1723.9941, 0)
	S008 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(1171.9516, 1520.2768, 0)
	P018 = App.Vector(1230.2893, 1312.2516, 0)
	S009 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(1320.3435, 916.1094, 0)
	P020 = App.Vector(1397.0134, 517.1606, 0)
	S010 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(1399.2520, 500.0081, 0)
	P022 = App.Vector(1400.0000, 482.7264, 0)
	S011 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(1400.0000, 0.0000, 0)
	S012 = Part.LineSegment(P022, P023)
	P024 = App.Vector(1600.0000, 0.0000, 0)
	S013 = Part.LineSegment(P023, P024)
	P025 = App.Vector(1600.0000, 396.0756, 0)
	S014 = Part.LineSegment(P024, P025)
	P026 = App.Vector(1594.3952, 501.8023, 0)
	P027 = App.Vector(1577.6438, 606.3438, 0)
	S015 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(1483.2509, 1010.2786, 0)
	P029 = App.Vector(1374.6093, 1410.6165, 0)
	S016 = Part.Arc(P027, P028, P029)
	P030 = App.Vector(1296.1155, 1647.1037, 0)
	P031 = App.Vector(1200.0000, 1876.9933, 0)
	S017 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(1094.3736, 2063.7655, 0)
	P033 = App.Vector(960.0323, 2231.0771, 0)
	S018 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(887.1216, 2282.0368, 0)
	P035 = App.Vector(800.0000, 2300.0000, 0)
	S019 = Part.Arc(P033, P034, P035)
	P036 = App.Vector(712.8784, 2282.0368, 0)
	P037 = App.Vector(639.9677, 2231.0771, 0)
	S020 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(505.6264, 2063.7655, 0)
	P039 = App.Vector(400.0000, 1876.9933, 0)
	S021 = Part.Arc(P037, P038, P039)
	P040 = App.Vector(303.8845, 1647.1037, 0)
	P041 = App.Vector(225.3907, 1410.6165, 0)
	S022 = Part.Arc(P039, P040, P041)
	P042 = App.Vector(116.7491, 1010.2786, 0)
	P043 = App.Vector(22.3562, 606.3438, 0)
	S023 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(5.6048, 501.8023, 0)
	P045 = App.Vector(0.0000, 396.0756, 0)
	S024 = Part.Arc(P043, P044, P045)
	P046 = App.Vector(0.0000, 0.0000, 0)
	S025 = Part.LineSegment(P045, P046)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door_faceDoor_Fa0():
	FC000 = ctr_face_door_faceDoor_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def door_faceDoor():
	FA000 = face_door_faceDoor_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_door_faceTop_Fa0_Ctr0():
	P000 = App.Vector(-800.0000, 0.0000, 0)
	P001 = App.Vector(-600.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-600.0000, 1000.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-800.0000, 1000.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-800.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door_faceTop_Fa0():
	FC000 = ctr_face_door_faceTop_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door_faceTop_Fa1_Ctr0():
	P000 = App.Vector(600.0000, 0.0000, 0)
	P001 = App.Vector(800.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(800.0000, 1000.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(600.0000, 1000.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(600.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door_faceTop_Fa1():
	FC000 = ctr_face_door_faceTop_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def door_faceTop():
	FA000 = face_door_faceTop_Fa0()
	FA001 = face_door_faceTop_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_door_faceSide_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(1000.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1000.0000, 2300.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 2300.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door_faceSide_Fa0():
	FC000 = ctr_face_door_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def door_faceSide():
	FA000 = face_door_faceSide_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_door():
	FIG = door_faceDoor()
	VEX = FIG.extrude(App.Vector(0, 0, 1000))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(0, 0, 0))
	return VFP
subpax_door = fex_subpax_door()

pax_door = subpax_door

pax_door.check()
#pax_door.exportBrep(f"{outFileName}.brep")
#pax_door.exportIges(f"{outFileName}.igs")
#pax_door.exportStep(f"{outFileName}.stp")
pax_door.exportStl(f"{outFileName}.stl")

