// Generated by Parametrix
ca_cabane_plancher_facePlancherTop_0 = [ [ 0.0000, 0.0000 ],[ 2602.4000, 0.0000 ],[ 2602.4000, 200.0000 ],[ 0.0000, 200.0000 ],[ 0.0000, 0.0000 ] ];
cb_cabane_plancher_facePlancherTop_0 = [  0, 1, 2, 3, 4 ];
ca_cabane_plancher_facePlancherTop_1 = [ [ 0.0000, 200.2000 ],[ 2602.4000, 200.2000 ],[ 2602.4000, 400.2000 ],[ 0.0000, 400.2000 ],[ 0.0000, 200.2000 ] ];
cb_cabane_plancher_facePlancherTop_1 = [  5, 6, 7, 8, 9 ];
ca_cabane_plancher_facePlancherTop_2 = [ [ 0.0000, 400.4000 ],[ 2602.4000, 400.4000 ],[ 2602.4000, 600.4000 ],[ 0.0000, 600.4000 ],[ 0.0000, 400.4000 ] ];
cb_cabane_plancher_facePlancherTop_2 = [  10, 11, 12, 13, 14 ];
ca_cabane_plancher_facePlancherTop_3 = [ [ 0.0000, 600.6000 ],[ 2602.4000, 600.6000 ],[ 2602.4000, 800.6000 ],[ 0.0000, 800.6000 ],[ 0.0000, 600.6000 ] ];
cb_cabane_plancher_facePlancherTop_3 = [  15, 16, 17, 18, 19 ];
ca_cabane_plancher_facePlancherTop_4 = [ [ 0.0000, 800.8000 ],[ 2602.4000, 800.8000 ],[ 2602.4000, 1000.8000 ],[ 0.0000, 1000.8000 ],[ 0.0000, 800.8000 ] ];
cb_cabane_plancher_facePlancherTop_4 = [  20, 21, 22, 23, 24 ];
ca_cabane_plancher_facePlancherTop_5 = [ [ 0.0000, 1001.0000 ],[ 2602.4000, 1001.0000 ],[ 2602.4000, 1201.0000 ],[ 0.0000, 1201.0000 ],[ 0.0000, 1001.0000 ] ];
cb_cabane_plancher_facePlancherTop_5 = [  25, 26, 27, 28, 29 ];
ca_cabane_plancher_facePlancherTop_6 = [ [ 0.0000, 1201.2000 ],[ 2602.4000, 1201.2000 ],[ 2602.4000, 1401.2000 ],[ 0.0000, 1401.2000 ],[ 0.0000, 1201.2000 ] ];
cb_cabane_plancher_facePlancherTop_6 = [  30, 31, 32, 33, 34 ];
ca_cabane_plancher_facePlancherTop_7 = [ [ 0.0000, 1401.4000 ],[ 2602.4000, 1401.4000 ],[ 2602.4000, 1601.4000 ],[ 0.0000, 1601.4000 ],[ 0.0000, 1401.4000 ] ];
cb_cabane_plancher_facePlancherTop_7 = [  35, 36, 37, 38, 39 ];
a_cabane_plancher_facePlancherTop = concat(ca_cabane_plancher_facePlancherTop_0, ca_cabane_plancher_facePlancherTop_1, ca_cabane_plancher_facePlancherTop_2, ca_cabane_plancher_facePlancherTop_3, ca_cabane_plancher_facePlancherTop_4, ca_cabane_plancher_facePlancherTop_5, ca_cabane_plancher_facePlancherTop_6, ca_cabane_plancher_facePlancherTop_7);
b_cabane_plancher_facePlancherTop = [cb_cabane_plancher_facePlancherTop_0, cb_cabane_plancher_facePlancherTop_1, cb_cabane_plancher_facePlancherTop_2, cb_cabane_plancher_facePlancherTop_3, cb_cabane_plancher_facePlancherTop_4, cb_cabane_plancher_facePlancherTop_5, cb_cabane_plancher_facePlancherTop_6, cb_cabane_plancher_facePlancherTop_7];
ca_cabane_plancher_facePlancherBottom_0 = [ [ 0.0000, 0.0000 ],[ 200.0000, 0.0000 ],[ 200.0000, 1601.4000 ],[ 0.0000, 1601.4000 ],[ 0.0000, 0.0000 ] ];
cb_cabane_plancher_facePlancherBottom_0 = [  0, 1, 2, 3, 4 ];
ca_cabane_plancher_facePlancherBottom_1 = [ [ 200.2000, 0.0000 ],[ 400.2000, 0.0000 ],[ 400.2000, 1601.4000 ],[ 200.2000, 1601.4000 ],[ 200.2000, 0.0000 ] ];
cb_cabane_plancher_facePlancherBottom_1 = [  5, 6, 7, 8, 9 ];
ca_cabane_plancher_facePlancherBottom_2 = [ [ 400.4000, 0.0000 ],[ 600.4000, 0.0000 ],[ 600.4000, 1601.4000 ],[ 400.4000, 1601.4000 ],[ 400.4000, 0.0000 ] ];
cb_cabane_plancher_facePlancherBottom_2 = [  10, 11, 12, 13, 14 ];
ca_cabane_plancher_facePlancherBottom_3 = [ [ 600.6000, 0.0000 ],[ 800.6000, 0.0000 ],[ 800.6000, 1601.4000 ],[ 600.6000, 1601.4000 ],[ 600.6000, 0.0000 ] ];
cb_cabane_plancher_facePlancherBottom_3 = [  15, 16, 17, 18, 19 ];
ca_cabane_plancher_facePlancherBottom_4 = [ [ 800.8000, 0.0000 ],[ 1000.8000, 0.0000 ],[ 1000.8000, 1601.4000 ],[ 800.8000, 1601.4000 ],[ 800.8000, 0.0000 ] ];
cb_cabane_plancher_facePlancherBottom_4 = [  20, 21, 22, 23, 24 ];
ca_cabane_plancher_facePlancherBottom_5 = [ [ 1001.0000, 0.0000 ],[ 1201.0000, 0.0000 ],[ 1201.0000, 1601.4000 ],[ 1001.0000, 1601.4000 ],[ 1001.0000, 0.0000 ] ];
cb_cabane_plancher_facePlancherBottom_5 = [  25, 26, 27, 28, 29 ];
ca_cabane_plancher_facePlancherBottom_6 = [ [ 1201.2000, 0.0000 ],[ 1401.2000, 0.0000 ],[ 1401.2000, 1601.4000 ],[ 1201.2000, 1601.4000 ],[ 1201.2000, 0.0000 ] ];
cb_cabane_plancher_facePlancherBottom_6 = [  30, 31, 32, 33, 34 ];
ca_cabane_plancher_facePlancherBottom_7 = [ [ 1401.4000, 0.0000 ],[ 1601.4000, 0.0000 ],[ 1601.4000, 1601.4000 ],[ 1401.4000, 1601.4000 ],[ 1401.4000, 0.0000 ] ];
cb_cabane_plancher_facePlancherBottom_7 = [  35, 36, 37, 38, 39 ];
ca_cabane_plancher_facePlancherBottom_8 = [ [ 1601.6000, 0.0000 ],[ 1801.6000, 0.0000 ],[ 1801.6000, 1601.4000 ],[ 1601.6000, 1601.4000 ],[ 1601.6000, 0.0000 ] ];
cb_cabane_plancher_facePlancherBottom_8 = [  40, 41, 42, 43, 44 ];
ca_cabane_plancher_facePlancherBottom_9 = [ [ 1801.8000, 0.0000 ],[ 2001.8000, 0.0000 ],[ 2001.8000, 1601.4000 ],[ 1801.8000, 1601.4000 ],[ 1801.8000, 0.0000 ] ];
cb_cabane_plancher_facePlancherBottom_9 = [  45, 46, 47, 48, 49 ];
ca_cabane_plancher_facePlancherBottom_10 = [ [ 2002.0000, 0.0000 ],[ 2202.0000, 0.0000 ],[ 2202.0000, 1601.4000 ],[ 2002.0000, 1601.4000 ],[ 2002.0000, 0.0000 ] ];
cb_cabane_plancher_facePlancherBottom_10 = [  50, 51, 52, 53, 54 ];
ca_cabane_plancher_facePlancherBottom_11 = [ [ 2202.2000, 0.0000 ],[ 2402.2000, 0.0000 ],[ 2402.2000, 1601.4000 ],[ 2202.2000, 1601.4000 ],[ 2202.2000, 0.0000 ] ];
cb_cabane_plancher_facePlancherBottom_11 = [  55, 56, 57, 58, 59 ];
ca_cabane_plancher_facePlancherBottom_12 = [ [ 2402.4000, 0.0000 ],[ 2602.4000, 0.0000 ],[ 2602.4000, 1601.4000 ],[ 2402.4000, 1601.4000 ],[ 2402.4000, 0.0000 ] ];
cb_cabane_plancher_facePlancherBottom_12 = [  60, 61, 62, 63, 64 ];
a_cabane_plancher_facePlancherBottom = concat(ca_cabane_plancher_facePlancherBottom_0, ca_cabane_plancher_facePlancherBottom_1, ca_cabane_plancher_facePlancherBottom_2, ca_cabane_plancher_facePlancherBottom_3, ca_cabane_plancher_facePlancherBottom_4, ca_cabane_plancher_facePlancherBottom_5, ca_cabane_plancher_facePlancherBottom_6, ca_cabane_plancher_facePlancherBottom_7, ca_cabane_plancher_facePlancherBottom_8, ca_cabane_plancher_facePlancherBottom_9, ca_cabane_plancher_facePlancherBottom_10, ca_cabane_plancher_facePlancherBottom_11, ca_cabane_plancher_facePlancherBottom_12);
b_cabane_plancher_facePlancherBottom = [cb_cabane_plancher_facePlancherBottom_0, cb_cabane_plancher_facePlancherBottom_1, cb_cabane_plancher_facePlancherBottom_2, cb_cabane_plancher_facePlancherBottom_3, cb_cabane_plancher_facePlancherBottom_4, cb_cabane_plancher_facePlancherBottom_5, cb_cabane_plancher_facePlancherBottom_6, cb_cabane_plancher_facePlancherBottom_7, cb_cabane_plancher_facePlancherBottom_8, cb_cabane_plancher_facePlancherBottom_9, cb_cabane_plancher_facePlancherBottom_10, cb_cabane_plancher_facePlancherBottom_11, cb_cabane_plancher_facePlancherBottom_12];
ca_cabane_plancher_faceBeam_0 = [ [ 200.0000, 400.0000 ],[ 350.0000, 400.0000 ],[ 350.0000, 335.0692 ],[ 335.0000, 250.0000 ],[ 200.0000, 250.0000 ],[ 200.0000, 400.0000 ] ];
cb_cabane_plancher_faceBeam_0 = [  0, 1, 2, 3, 4, 5 ];
ca_cabane_plancher_faceBeam_1 = [ [ 1401.4000, 400.0000 ],[ 1251.4000, 400.0000 ],[ 1251.4000, 335.0692 ],[ 1266.4000, 250.0000 ],[ 1401.4000, 250.0000 ],[ 1401.4000, 400.0000 ] ];
cb_cabane_plancher_faceBeam_1 = [  6, 7, 8, 9, 10, 11 ];
a_cabane_plancher_faceBeam = concat(ca_cabane_plancher_faceBeam_0, ca_cabane_plancher_faceBeam_1);
b_cabane_plancher_faceBeam = [cb_cabane_plancher_faceBeam_0, cb_cabane_plancher_faceBeam_1];
ca_cabane_plancher_faceLeg_0 = [ [ 513.7630, 400.0000 ],[ 361.4490, 400.0000 ],[ 290.9183, 0.0000 ],[ 443.2322, 0.0000 ],[ 513.7630, 400.0000 ] ];
cb_cabane_plancher_faceLeg_0 = [  0, 1, 2, 3, 4 ];
ca_cabane_plancher_faceLeg_1 = [ [ 1087.6370, 400.0000 ],[ 1239.9510, 400.0000 ],[ 1310.4817, 0.0000 ],[ 1158.1678, 0.0000 ],[ 1087.6370, 400.0000 ] ];
cb_cabane_plancher_faceLeg_1 = [  5, 6, 7, 8, 9 ];
a_cabane_plancher_faceLeg = concat(ca_cabane_plancher_faceLeg_0, ca_cabane_plancher_faceLeg_1);
b_cabane_plancher_faceLeg = [cb_cabane_plancher_faceLeg_0, cb_cabane_plancher_faceLeg_1];
ca_cabane_plancher_faceButtress_0 = [ [ 513.7630, 400.0000 ],[ 1087.6370, 400.0000 ],[ 1114.0860, 250.0000 ],[ 487.3140, 250.0000 ],[ 513.7630, 400.0000 ] ];
cb_cabane_plancher_faceButtress_0 = [  0, 1, 2, 3, 4 ];
a_cabane_plancher_faceButtress = concat(ca_cabane_plancher_faceButtress_0);
b_cabane_plancher_faceButtress = [cb_cabane_plancher_faceButtress_0];
ca_cabane_plancher_faceSide_0 = [ [ 200.0000, 0.0000 ],[ 300.0000, 0.0000 ],[ 300.0000, 400.0000 ],[ 200.0000, 400.0000 ],[ 200.0000, 0.0000 ] ];
cb_cabane_plancher_faceSide_0 = [  0, 1, 2, 3, 4 ];
ca_cabane_plancher_faceSide_1 = [ [ 2302.4000, 0.0000 ],[ 2402.4000, 0.0000 ],[ 2402.4000, 400.0000 ],[ 2302.4000, 400.0000 ],[ 2302.4000, 0.0000 ] ];
cb_cabane_plancher_faceSide_1 = [  5, 6, 7, 8, 9 ];
a_cabane_plancher_faceSide = concat(ca_cabane_plancher_faceSide_0, ca_cabane_plancher_faceSide_1);
b_cabane_plancher_faceSide = [cb_cabane_plancher_faceSide_0, cb_cabane_plancher_faceSide_1];

module subpax_cabane_plancher_plancherTop () {
	translate( [ 0, 0, 420 ])
		rotate( [ 0, 0, 0 ])
			   linear_extrude(height = 20) polygon(a_cabane_plancher_facePlancherTop, b_cabane_plancher_facePlancherTop);
}

module subpax_cabane_plancher_plancherBottom () {
	translate( [ 0, 0, 400 ])
		rotate( [ 0, 0, 0 ])
			   linear_extrude(height = 20) polygon(a_cabane_plancher_facePlancherBottom, b_cabane_plancher_facePlancherBottom);
}

module subpax_cabane_plancher_beam () {
	translate( [ 2602.4, 1601.4000000000003, 0 ])
		rotate( [ 90, 0, -90 ])
			   linear_extrude(height = 2602.4) polygon(a_cabane_plancher_faceBeam, b_cabane_plancher_faceBeam);
}

module subpax_cabane_plancher_leg1 () {
	translate( [ 300, 1601.4, 0 ])
		rotate( [ 90, 0, -90 ])
			   linear_extrude(height = 100) polygon(a_cabane_plancher_faceLeg, b_cabane_plancher_faceLeg);
}

module subpax_cabane_plancher_leg2 () {
	translate( [ 2402.4, 1601.4000000000003, 0 ])
		rotate( [ 90, 0, -90 ])
			   linear_extrude(height = 100) polygon(a_cabane_plancher_faceLeg, b_cabane_plancher_faceLeg);
}

module subpax_cabane_plancher_buttress1 () {
	translate( [ 300, 1601.4, 0 ])
		rotate( [ 90, 0, -90 ])
			   linear_extrude(height = 100) polygon(a_cabane_plancher_faceButtress, b_cabane_plancher_faceButtress);
}

module subpax_cabane_plancher_buttress2 () {
	translate( [ 2402.4, 1601.4000000000003, 0 ])
		rotate( [ 90, 0, -90 ])
			   linear_extrude(height = 100) polygon(a_cabane_plancher_faceButtress, b_cabane_plancher_faceButtress);
}

module pax_cabane_plancher () {
	union () {
		subpax_cabane_plancher_plancherTop();
subpax_cabane_plancher_plancherBottom();
subpax_cabane_plancher_beam();
subpax_cabane_plancher_leg1();
subpax_cabane_plancher_leg2();
subpax_cabane_plancher_buttress1();
subpax_cabane_plancher_buttress2();
	}
}

pax_cabane_plancher();
