// Generated by Parametrix

const { polygon } = require('@jscad/modeling').primitives;
//const { subtract } = require('@jscad/modeling').booleans;
//const { union, intersect, scission, subtract } = require('@jscad/modeling').booleans;
const { union, intersect, subtract } = require('@jscad/modeling').booleans;
const { extrudeLinear, extrudeRotate } = require('@jscad/modeling').extrusions;
const { translate, rotate } = require('@jscad/modeling').transforms;

const main = () => {

const ctr_face_fig_cabane_plancher_facePlancherTop_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 2602.4000, 0.0000 ],
	[ 2602.4000, 200.0000 ],
	[ 0.0000, 200.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherTop_Fa000 = ctr_face_fig_cabane_plancher_facePlancherTop_Fa000_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherTop_Fa001_Ctr000 = polygon({ points: [ [ 0.0000, 200.2000 ],
	[ 2602.4000, 200.2000 ],
	[ 2602.4000, 400.2000 ],
	[ 0.0000, 400.2000 ],
	[ 0.0000, 200.2000 ] ] });

face_fig_cabane_plancher_facePlancherTop_Fa001 = ctr_face_fig_cabane_plancher_facePlancherTop_Fa001_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherTop_Fa002_Ctr000 = polygon({ points: [ [ 0.0000, 400.4000 ],
	[ 2602.4000, 400.4000 ],
	[ 2602.4000, 600.4000 ],
	[ 0.0000, 600.4000 ],
	[ 0.0000, 400.4000 ] ] });

face_fig_cabane_plancher_facePlancherTop_Fa002 = ctr_face_fig_cabane_plancher_facePlancherTop_Fa002_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherTop_Fa003_Ctr000 = polygon({ points: [ [ 0.0000, 600.6000 ],
	[ 2602.4000, 600.6000 ],
	[ 2602.4000, 800.6000 ],
	[ 0.0000, 800.6000 ],
	[ 0.0000, 600.6000 ] ] });

face_fig_cabane_plancher_facePlancherTop_Fa003 = ctr_face_fig_cabane_plancher_facePlancherTop_Fa003_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherTop_Fa004_Ctr000 = polygon({ points: [ [ 0.0000, 800.8000 ],
	[ 2602.4000, 800.8000 ],
	[ 2602.4000, 1000.8000 ],
	[ 0.0000, 1000.8000 ],
	[ 0.0000, 800.8000 ] ] });

face_fig_cabane_plancher_facePlancherTop_Fa004 = ctr_face_fig_cabane_plancher_facePlancherTop_Fa004_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherTop_Fa005_Ctr000 = polygon({ points: [ [ 0.0000, 1001.0000 ],
	[ 2602.4000, 1001.0000 ],
	[ 2602.4000, 1201.0000 ],
	[ 0.0000, 1201.0000 ],
	[ 0.0000, 1001.0000 ] ] });

face_fig_cabane_plancher_facePlancherTop_Fa005 = ctr_face_fig_cabane_plancher_facePlancherTop_Fa005_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherTop_Fa006_Ctr000 = polygon({ points: [ [ 0.0000, 1201.2000 ],
	[ 2602.4000, 1201.2000 ],
	[ 2602.4000, 1401.2000 ],
	[ 0.0000, 1401.2000 ],
	[ 0.0000, 1201.2000 ] ] });

face_fig_cabane_plancher_facePlancherTop_Fa006 = ctr_face_fig_cabane_plancher_facePlancherTop_Fa006_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherTop_Fa007_Ctr000 = polygon({ points: [ [ 0.0000, 1401.4000 ],
	[ 2602.4000, 1401.4000 ],
	[ 2602.4000, 1601.4000 ],
	[ 0.0000, 1601.4000 ],
	[ 0.0000, 1401.4000 ] ] });

face_fig_cabane_plancher_facePlancherTop_Fa007 = ctr_face_fig_cabane_plancher_facePlancherTop_Fa007_Ctr000;
fig_cabane_plancher_facePlancherTop = union( face_fig_cabane_plancher_facePlancherTop_Fa000, face_fig_cabane_plancher_facePlancherTop_Fa001, face_fig_cabane_plancher_facePlancherTop_Fa002, face_fig_cabane_plancher_facePlancherTop_Fa003, face_fig_cabane_plancher_facePlancherTop_Fa004, face_fig_cabane_plancher_facePlancherTop_Fa005, face_fig_cabane_plancher_facePlancherTop_Fa006, face_fig_cabane_plancher_facePlancherTop_Fa007 );
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 200.0000, 0.0000 ],
	[ 200.0000, 1601.4000 ],
	[ 0.0000, 1601.4000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa000 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa000_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa001_Ctr000 = polygon({ points: [ [ 200.2000, 0.0000 ],
	[ 400.2000, 0.0000 ],
	[ 400.2000, 1601.4000 ],
	[ 200.2000, 1601.4000 ],
	[ 200.2000, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa001 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa001_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa002_Ctr000 = polygon({ points: [ [ 400.4000, 0.0000 ],
	[ 600.4000, 0.0000 ],
	[ 600.4000, 1601.4000 ],
	[ 400.4000, 1601.4000 ],
	[ 400.4000, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa002 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa002_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa003_Ctr000 = polygon({ points: [ [ 600.6000, 0.0000 ],
	[ 800.6000, 0.0000 ],
	[ 800.6000, 1601.4000 ],
	[ 600.6000, 1601.4000 ],
	[ 600.6000, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa003 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa003_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa004_Ctr000 = polygon({ points: [ [ 800.8000, 0.0000 ],
	[ 1000.8000, 0.0000 ],
	[ 1000.8000, 1601.4000 ],
	[ 800.8000, 1601.4000 ],
	[ 800.8000, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa004 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa004_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa005_Ctr000 = polygon({ points: [ [ 1001.0000, 0.0000 ],
	[ 1201.0000, 0.0000 ],
	[ 1201.0000, 1601.4000 ],
	[ 1001.0000, 1601.4000 ],
	[ 1001.0000, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa005 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa005_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa006_Ctr000 = polygon({ points: [ [ 1201.2000, 0.0000 ],
	[ 1401.2000, 0.0000 ],
	[ 1401.2000, 1601.4000 ],
	[ 1201.2000, 1601.4000 ],
	[ 1201.2000, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa006 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa006_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa007_Ctr000 = polygon({ points: [ [ 1401.4000, 0.0000 ],
	[ 1601.4000, 0.0000 ],
	[ 1601.4000, 1601.4000 ],
	[ 1401.4000, 1601.4000 ],
	[ 1401.4000, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa007 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa007_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa008_Ctr000 = polygon({ points: [ [ 1601.6000, 0.0000 ],
	[ 1801.6000, 0.0000 ],
	[ 1801.6000, 1601.4000 ],
	[ 1601.6000, 1601.4000 ],
	[ 1601.6000, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa008 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa008_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa009_Ctr000 = polygon({ points: [ [ 1801.8000, 0.0000 ],
	[ 2001.8000, 0.0000 ],
	[ 2001.8000, 1601.4000 ],
	[ 1801.8000, 1601.4000 ],
	[ 1801.8000, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa009 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa009_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa010_Ctr000 = polygon({ points: [ [ 2002.0000, 0.0000 ],
	[ 2202.0000, 0.0000 ],
	[ 2202.0000, 1601.4000 ],
	[ 2002.0000, 1601.4000 ],
	[ 2002.0000, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa010 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa010_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa011_Ctr000 = polygon({ points: [ [ 2202.2000, 0.0000 ],
	[ 2402.2000, 0.0000 ],
	[ 2402.2000, 1601.4000 ],
	[ 2202.2000, 1601.4000 ],
	[ 2202.2000, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa011 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa011_Ctr000;
const ctr_face_fig_cabane_plancher_facePlancherBottom_Fa012_Ctr000 = polygon({ points: [ [ 2402.4000, 0.0000 ],
	[ 2602.4000, 0.0000 ],
	[ 2602.4000, 1601.4000 ],
	[ 2402.4000, 1601.4000 ],
	[ 2402.4000, 0.0000 ] ] });

face_fig_cabane_plancher_facePlancherBottom_Fa012 = ctr_face_fig_cabane_plancher_facePlancherBottom_Fa012_Ctr000;
fig_cabane_plancher_facePlancherBottom = union( face_fig_cabane_plancher_facePlancherBottom_Fa000, face_fig_cabane_plancher_facePlancherBottom_Fa001, face_fig_cabane_plancher_facePlancherBottom_Fa002, face_fig_cabane_plancher_facePlancherBottom_Fa003, face_fig_cabane_plancher_facePlancherBottom_Fa004, face_fig_cabane_plancher_facePlancherBottom_Fa005, face_fig_cabane_plancher_facePlancherBottom_Fa006, face_fig_cabane_plancher_facePlancherBottom_Fa007, face_fig_cabane_plancher_facePlancherBottom_Fa008, face_fig_cabane_plancher_facePlancherBottom_Fa009, face_fig_cabane_plancher_facePlancherBottom_Fa010, face_fig_cabane_plancher_facePlancherBottom_Fa011, face_fig_cabane_plancher_facePlancherBottom_Fa012 );
const ctr_face_fig_cabane_plancher_faceBeam_Fa000_Ctr000 = polygon({ points: [ [ 200.0000, 400.0000 ],
	[ 350.0000, 400.0000 ],
	[ 350.0000, 335.0692 ],
	[ 335.0000, 250.0000 ],
	[ 200.0000, 250.0000 ],
	[ 200.0000, 400.0000 ] ] });

face_fig_cabane_plancher_faceBeam_Fa000 = ctr_face_fig_cabane_plancher_faceBeam_Fa000_Ctr000;
const ctr_face_fig_cabane_plancher_faceBeam_Fa001_Ctr000 = polygon({ points: [ [ 1401.4000, 400.0000 ],
	[ 1251.4000, 400.0000 ],
	[ 1251.4000, 335.0692 ],
	[ 1266.4000, 250.0000 ],
	[ 1401.4000, 250.0000 ],
	[ 1401.4000, 400.0000 ] ] });

face_fig_cabane_plancher_faceBeam_Fa001 = ctr_face_fig_cabane_plancher_faceBeam_Fa001_Ctr000;
fig_cabane_plancher_faceBeam = union( face_fig_cabane_plancher_faceBeam_Fa000, face_fig_cabane_plancher_faceBeam_Fa001 );
const ctr_face_fig_cabane_plancher_faceLeg_Fa000_Ctr000 = polygon({ points: [ [ 513.7630, 400.0000 ],
	[ 361.4490, 400.0000 ],
	[ 290.9183, 0.0000 ],
	[ 443.2322, 0.0000 ],
	[ 513.7630, 400.0000 ] ] });

face_fig_cabane_plancher_faceLeg_Fa000 = ctr_face_fig_cabane_plancher_faceLeg_Fa000_Ctr000;
const ctr_face_fig_cabane_plancher_faceLeg_Fa001_Ctr000 = polygon({ points: [ [ 1087.6370, 400.0000 ],
	[ 1239.9510, 400.0000 ],
	[ 1310.4817, 0.0000 ],
	[ 1158.1678, 0.0000 ],
	[ 1087.6370, 400.0000 ] ] });

face_fig_cabane_plancher_faceLeg_Fa001 = ctr_face_fig_cabane_plancher_faceLeg_Fa001_Ctr000;
fig_cabane_plancher_faceLeg = union( face_fig_cabane_plancher_faceLeg_Fa000, face_fig_cabane_plancher_faceLeg_Fa001 );
const ctr_face_fig_cabane_plancher_faceButtress_Fa000_Ctr000 = polygon({ points: [ [ 513.7630, 400.0000 ],
	[ 1087.6370, 400.0000 ],
	[ 1114.0860, 250.0000 ],
	[ 487.3140, 250.0000 ],
	[ 513.7630, 400.0000 ] ] });

face_fig_cabane_plancher_faceButtress_Fa000 = ctr_face_fig_cabane_plancher_faceButtress_Fa000_Ctr000;
fig_cabane_plancher_faceButtress = face_fig_cabane_plancher_faceButtress_Fa000;
const ctr_face_fig_cabane_plancher_faceSide_Fa000_Ctr000 = polygon({ points: [ [ 200.0000, 0.0000 ],
	[ 300.0000, 0.0000 ],
	[ 300.0000, 400.0000 ],
	[ 200.0000, 400.0000 ],
	[ 200.0000, 0.0000 ] ] });

face_fig_cabane_plancher_faceSide_Fa000 = ctr_face_fig_cabane_plancher_faceSide_Fa000_Ctr000;
const ctr_face_fig_cabane_plancher_faceSide_Fa001_Ctr000 = polygon({ points: [ [ 2302.4000, 0.0000 ],
	[ 2402.4000, 0.0000 ],
	[ 2402.4000, 400.0000 ],
	[ 2302.4000, 400.0000 ],
	[ 2302.4000, 0.0000 ] ] });

face_fig_cabane_plancher_faceSide_Fa001 = ctr_face_fig_cabane_plancher_faceSide_Fa001_Ctr000;
fig_cabane_plancher_faceSide = union( face_fig_cabane_plancher_faceSide_Fa000, face_fig_cabane_plancher_faceSide_Fa001 );

const subpax_cabane_plancher_plancherTop =
	translate( [ 0, 0, 420, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 20}, fig_cabane_plancher_facePlancherTop )
		)
	);


const subpax_cabane_plancher_plancherBottom =
	translate( [ 0, 0, 400, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 20}, fig_cabane_plancher_facePlancherBottom )
		)
	);


const subpax_cabane_plancher_beam =
	translate( [ 2602.4, 1601.4000000000003, 0, ],
		rotate( [ 1.5707963267948966, 0, -1.5707963267948966, ],
			   extrudeLinear( {height: 2602.4}, fig_cabane_plancher_faceBeam )
		)
	);


const subpax_cabane_plancher_leg1 =
	translate( [ 300, 1601.4, 0, ],
		rotate( [ 1.5707963267948966, 0, -1.5707963267948966, ],
			   extrudeLinear( {height: 100}, fig_cabane_plancher_faceLeg )
		)
	);


const subpax_cabane_plancher_leg2 =
	translate( [ 2402.4, 1601.4000000000003, 0, ],
		rotate( [ 1.5707963267948966, 0, -1.5707963267948966, ],
			   extrudeLinear( {height: 100}, fig_cabane_plancher_faceLeg )
		)
	);


const subpax_cabane_plancher_buttress1 =
	translate( [ 300, 1601.4, 0, ],
		rotate( [ 1.5707963267948966, 0, -1.5707963267948966, ],
			   extrudeLinear( {height: 100}, fig_cabane_plancher_faceButtress )
		)
	);


const subpax_cabane_plancher_buttress2 =
	translate( [ 2402.4, 1601.4000000000003, 0, ],
		rotate( [ 1.5707963267948966, 0, -1.5707963267948966, ],
			   extrudeLinear( {height: 100}, fig_cabane_plancher_faceButtress )
		)
	);

const pax_cabane_plancher = union( subpax_cabane_plancher_plancherTop, subpax_cabane_plancher_plancherBottom, subpax_cabane_plancher_beam, subpax_cabane_plancher_leg1, subpax_cabane_plancher_leg2, subpax_cabane_plancher_buttress1, subpax_cabane_plancher_buttress2 );

return pax_cabane_plancher;
}
module.exports = { main };
